#!/usr/bin/env python3
"""T-P21-3 — Write latest optimised params to configs/envs/opt_params.env.

Reads the most recent is_current=TRUE row per (symbol, timeframe) from
optimization_runs, aggregates best_params across symbols (median for floats,
mode for ints), and writes OPT_* env vars to a file loaded by Settings.

Usage
─────
  uv run python scripts/write_opt_params.py
  uv run python scripts/write_opt_params.py --symbols BTC/USDT ETH/USDT
  uv run python scripts/write_opt_params.py --dry-run
"""
from __future__ import annotations

import argparse
import asyncio
import json
import logging
import statistics
from datetime import datetime, timezone
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s  %(levelname)-7s  %(message)s",
                    datefmt="%H:%M:%S")
log = logging.getLogger(__name__)

# Maps optimization_runs.best_params key → Settings opt_* field name
_PARAM_TO_ENV: dict[str, str] = {
    "atr_mult":              "OPT_ATR_MULT",
    "rr_ratio":              "OPT_RR_RATIO",
    "kelly_frac":            "OPT_KELLY_FRAC",
    "trailing_atr_mult":     "OPT_TRAILING_ATR_MULT",
    "trailing_trigger_pct":  "OPT_TRAILING_TRIGGER_PCT",
    "breakeven_trigger_pct": "OPT_BREAKEVEN_TRIGGER_PCT",
    "pullback_atr_frac":     "OPT_PULLBACK_ATR_FRAC",
    "sl_cooldown_bars":      "OPT_SL_COOLDOWN_BARS",
    "min_conf_high_vol":     "OPT_MIN_CONF_HIGH_VOL",
}

_INT_PARAMS = {"sl_cooldown_bars"}

DEFAULT_OUT = Path("configs/envs/opt_params.env")


async def _fetch_params(symbols: list[str], timeframe: str) -> list[dict]:
    from sqlalchemy import text
    from smart_trader.data.storage.database import get_session_factory

    factory = get_session_factory()
    async with factory() as session:
        rows = await session.execute(
            text("""
                SELECT symbol, best_params, test_score, test_sharpe, created_at
                FROM optimization_runs
                WHERE is_current = TRUE
                  AND timeframe  = :tf
                  AND symbol     = ANY(:syms)
                ORDER BY created_at DESC
            """),
            {"tf": timeframe, "syms": symbols},
        )
        return [dict(r._mapping) for r in rows]


def _aggregate(rows: list[dict]) -> dict[str, float | int]:
    """Median across symbols for each param key."""
    by_key: dict[str, list[float]] = {}
    for row in rows:
        params = json.loads(row["best_params"]) if isinstance(row["best_params"], str) else row["best_params"]
        for k, v in params.items():
            by_key.setdefault(k, []).append(float(v))

    agg: dict[str, float | int] = {}
    for k, vals in by_key.items():
        med = statistics.median(vals)
        agg[k] = round(med) if k in _INT_PARAMS else round(med, 6)
    return agg


def _write_env(params: dict, out: Path, dry_run: bool) -> None:
    lines = [
        f"# Auto-generated by write_opt_params.py — {datetime.now(timezone.utc).isoformat()}",
        "# DO NOT edit manually — overwritten on next optimization run.",
        "",
    ]
    for param_key, env_key in _PARAM_TO_ENV.items():
        val = params.get(param_key)
        if val is not None:
            lines.append(f"{env_key}={val}")

    content = "\n".join(lines) + "\n"
    if dry_run:
        print("── dry-run: would write to", out, "──")
        print(content)
        return

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content)
    log.info(f"Written → {out}")


async def _run(symbols: list[str], timeframe: str, out: Path, dry_run: bool) -> int:
    rows = await _fetch_params(symbols, timeframe)
    if not rows:
        log.error("No is_current=TRUE rows found in optimization_runs — nothing written.")
        return 1

    log.info(f"Found {len(rows)} current rows for {symbols}")
    for r in rows:
        log.info(f"  {r['symbol']:12s}  score={r['test_score']:.4f}  sharpe={r['test_sharpe']:.2f}"
                 f"  at={r['created_at']}")

    params = _aggregate(rows)
    log.info("Aggregated params (median across symbols):")
    for k, v in params.items():
        env_key = _PARAM_TO_ENV.get(k, k.upper())
        log.info(f"  {env_key}={v}")

    _write_env(params, out, dry_run)
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(description="Write latest opt params to env file")
    parser.add_argument("--symbols",   nargs="+", default=["BTC/USDT", "ETH/USDT"])
    parser.add_argument("--timeframe", default="1h")
    parser.add_argument("--out",       type=Path, default=DEFAULT_OUT,
                        help=f"Output path (default: {DEFAULT_OUT})")
    parser.add_argument("--dry-run",   action="store_true",
                        help="Print params without writing")
    args = parser.parse_args()

    rc = asyncio.run(_run(args.symbols, args.timeframe, args.out, args.dry_run))
    raise SystemExit(rc)


if __name__ == "__main__":
    main()
